# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Matrix": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://VladislavYak.github.io/test/"

git_url = "https://github.com/VladislavYak/test/tree/{branch}/"

def custom_doc_links(name): return None
