# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Matrix']

# Cell
import numpy

class Matrix():
    """
    Class generates a zero matrix
    """
    def __init__(self, n_matrix:int, m_matrix:int):
        self.n = n_matrix
        self.m = m_matrix
    def make_matrix(self):
        return numpy.zeros(self.n * self.m).reshape(self.n, self.m)